# command line: D:\PycharmProjects\CTR-GCN-main\few_shot.py --config config/nturgbd-cross-subject/default.yaml

base_lr: 0.1
batch_size: 64
config: config/nturgbd-cross-subject/default.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder_ntu.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.ctrgcn.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ''
nesterov: true
num_epoch: 65
num_worker: 32
optimizer: SGD
phase: train
print_log: true
sample: meta.sample.Sample
save_epoch: 30
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 35
- 55
test_batch_size: 64
test_feeder_args:
  bone: false
  data_path: data/ntu/NTU60_CS.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: data/ntu/NTU60_CS.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: false
  window_size: 64
train_sampler_args:
  k_shot: 1
  n_episodes: 100
  n_way: 5
  q_query: 15
warm_up_epoch: 5
weight_decay: 0.0004
weights: null
work_dir: ./work_dir/ntu60/xsub/ctrgcn_joint
